// UI translations only. Navigation and arrow positions live in tour-routes.js.
export const I18N={
  en:{
    pageTitle:'M7A Building — Virtual Tour | University of Sharjah',eyebrow:'University of Sharjah · Virtual Tour',building:'M7A Building',university:'University of Sharjah',buildingLoader:'Building M7A',
    viewControls:'View controls',motionTitle:'Use phone motion',motionEnable:'Enable phone motion view',motionDisable:'Disable phone motion view',tourMap:'Campus map',openMap:'Back to campus map',tourInfo:'Tour information',openInfo:'Open tour information',resetView:'Reset and level view',fullScreen:'Full screen',exitFullScreen:'Exit full screen',
    campusMapTitle:'M7 · College of Science',campusMapSubtitle:'A 360° indoor tour is available',m7Hall:'M7 Hall',indoorTour:'360° indoor tour',enterHall:'Enter M7',backToCampus:'Back to campus',campusMapAria:'Interactive University of Sharjah campus map',currentCheckpoint:'Current checkpoint',viewPanorama:'View in 360°',preparingPanorama:'Preparing 360° view…',mapTitle:'M7A Tour Map',mapSubtitle:'Find your place in the building',closeMap:'Close map',youAreHere:'You are here',mapFloor:'Map floor',groundFloor:'Ground Floor',topFloor:'Top Floor',groundFloorBadge:'Ground Floor',topFloorBadge:'Top Floor',groundMapTitle:'Ground floor map',groundMapDesc:'Facing into the hallway from the entrance at the bottom: M7A-001 is on the right and M7A-004 is on the left at Study Rooms. At Hall End, M7A-003 is on the left and M7A-002 is on the right. The stairs are on the right below M7A-001 and connect the entrance to the top floor. Elevators are on the left of the entrance. Schematic, not to scale.',topMapTitle:'Top floor map',topMapDesc:'Stairs from the entrance lead to Stair Landing, then Faculty Offices, then Seating Area. Schematic, not to scale.',
    hallEnd:'Hall End',studyRooms:'Study Rooms',stairsUp:'Stairs ↑',elevators:'Elevators',entrance:'Entrance',seatingArea:'Seating Area',facultyOffices:'Faculty Offices',stairLanding:'Stair Landing',entranceGround:'↓ Entrance · Ground Floor',groundMapNote:'Facing into the hall from the entrance. M7A-001 is on your right.',topMapNote:'The stairs connect this floor to the ground-floor entrance.',mapHelp:'Tap a location to go there. Highlighted location = you are here. Schematic · not to scale.',
    aboutTitle:'About this tour',aboutSubtitle:'University of Sharjah · Building M7A',closeInfo:'Close information',aboutCopy:'Drag to look around. Use a floor arrow or the map to move between locations. On supported phones, you can also look around by moving your device.',shareTitle:'Share this location',copyLink:'Copy link',linkCopied:'Link copied',copyFailed:'Could not copy the link.',
    tourNavigation:'Tour navigation',navigationTitle:'Tap a floor arrow to move · Backspace: back · Home: reset view',back:'Back',loadingM7A:'Loading M7A',loading:'Loading M7A…',loadingPct:p=>`Loading M7A · ${p}%`,preparing:'Preparing M7A view…',stillLoading:'Still loading M7A…',
    drag:'Drag to look around.',moveOrDrag:'Move your phone or drag to look around.',tapArrow:'Tap a floor arrow to move.',goTo:n=>`Go to ${n}`,downstairs:'Downstairs · Entrance',upstairs:'Upstairs · Stair Landing',loadingNext:'Loading next view…',loadingNextPct:p=>`Loading next view · ${p}%`,preparingNext:'Preparing next view…',loadLocationError:'This location could not load. Please try again.',
    motionOff:'Phone motion view off.',motionOn:'Phone motion view on · move your phone to look around.',motionDenied:'Phone motion access was not allowed. You can still drag to look around.',fullscreenUnavailable:'Full screen is unavailable in this browser.',tourLoadError:'Could not load the tour.',checkConnection:'Check your connection and reload this page.',retry:'Retry',campusGuide:'Campus guide PDF ↗',switchLanguage:'Switch to Arabic'
  },
  ar:{
    pageTitle:'مبنى M7A — جولة افتراضية | جامعة الشارقة',eyebrow:'جامعة الشارقة · جولة افتراضية',building:'مبنى M7A',university:'جامعة الشارقة',buildingLoader:'مبنى M7A',
    viewControls:'أدوات العرض',motionTitle:'استخدام حركة الهاتف',motionEnable:'تفعيل العرض بحركة الهاتف',motionDisable:'إيقاف العرض بحركة الهاتف',tourMap:'خريطة الحرم الجامعي',openMap:'العودة إلى خريطة الحرم الجامعي',tourInfo:'معلومات الجولة',openInfo:'فتح معلومات الجولة',resetView:'إعادة ضبط العرض وتسويته',fullScreen:'ملء الشاشة',exitFullScreen:'الخروج من ملء الشاشة',
    campusMapTitle:'M7 · كلية العلوم',campusMapSubtitle:'تتوفر جولة داخلية بزاوية 360°',m7Hall:'مبنى M7',indoorTour:'جولة داخلية بزاوية 360°',enterHall:'دخول M7',backToCampus:'العودة إلى الحرم',campusMapAria:'خريطة تفاعلية للحرم الجامعي في جامعة الشارقة',currentCheckpoint:'النقطة الحالية',viewPanorama:'عرض بزاوية 360°',preparingPanorama:'جارٍ تجهيز العرض بزاوية 360°…',mapTitle:'خريطة جولة M7A',mapSubtitle:'تعرّف على موقعك داخل المبنى',closeMap:'إغلاق الخريطة',youAreHere:'موقعك الحالي',mapFloor:'طابق الخريطة',groundFloor:'الطابق الأرضي',topFloor:'الطابق العلوي',groundFloorBadge:'الأرضي',topFloorBadge:'العلوي',groundMapTitle:'خريطة الطابق الأرضي',groundMapDesc:'عند النظر إلى الممر من المدخل في الأسفل: تقع M7A-001 على اليمين وM7A-004 على اليسار عند قاعات الدراسة. عند نهاية الردهة تقع M7A-003 على اليسار وM7A-002 على اليمين. يقع الدرج على اليمين أسفل M7A-001 ويربط المدخل بالطابق العلوي. تقع المصاعد على يسار المدخل. الخريطة توضيحية وغير مرسومة بمقياس.',topMapTitle:'خريطة الطابق العلوي',topMapDesc:'يؤدي الدرج من المدخل إلى بسطة الدرج، ثم مكاتب أعضاء هيئة التدريس، ثم منطقة الجلوس. الخريطة توضيحية وغير مرسومة بمقياس.',
    hallEnd:'نهاية الردهة',studyRooms:'قاعات الدراسة',stairsUp:'الدرج ↑',elevators:'المصاعد',entrance:'المدخل',seatingArea:'منطقة الجلوس',facultyOffices:'مكاتب أعضاء هيئة التدريس',stairLanding:'بسطة الدرج',entranceGround:'↓ المدخل · الطابق الأرضي',groundMapNote:'انظر إلى داخل الردهة من المدخل. تقع M7A-001 على يمينك.',topMapNote:'يربط الدرج هذا الطابق بمدخل الطابق الأرضي.',mapHelp:'اضغط على موقع للانتقال إليه. الموقع المميز هو موقعك الحالي. الخريطة توضيحية وغير مرسومة بمقياس.',
    aboutTitle:'حول هذه الجولة',aboutSubtitle:'جامعة الشارقة · مبنى M7A',closeInfo:'إغلاق المعلومات',aboutCopy:'اسحب للنظر حولك. استخدم سهمًا أرضيًا أو الخريطة للتنقل بين المواقع. في الهواتف المدعومة، يمكنك أيضًا النظر حولك بتحريك جهازك.',shareTitle:'مشاركة هذا الموقع',copyLink:'نسخ الرابط',linkCopied:'تم نسخ الرابط',copyFailed:'تعذّر نسخ الرابط.',
    tourNavigation:'التنقل في الجولة',navigationTitle:'اضغط على سهم أرضي للانتقال · مسافة للخلف: رجوع · الرئيسية: إعادة ضبط العرض',back:'رجوع',loadingM7A:'جارٍ تحميل M7A',loading:'جارٍ تحميل M7A…',loadingPct:p=>`جارٍ تحميل M7A · ${p}%`,preparing:'جارٍ تجهيز مشهد M7A…',stillLoading:'لا يزال تحميل M7A جاريًا…',
    drag:'اسحب للنظر حولك.',moveOrDrag:'حرّك هاتفك أو اسحب للنظر حولك.',tapArrow:'اضغط على سهم أرضي للانتقال.',goTo:n=>`الانتقال إلى ${n}`,downstairs:'إلى الأسفل · المدخل',upstairs:'إلى الأعلى · بسطة الدرج',loadingNext:'جارٍ تحميل المشهد التالي…',loadingNextPct:p=>`جارٍ تحميل المشهد التالي · ${p}%`,preparingNext:'جارٍ تجهيز المشهد التالي…',loadLocationError:'تعذّر تحميل هذا الموقع. حاول مرة أخرى.',
    motionOff:'تم إيقاف العرض بحركة الهاتف.',motionOn:'تم تفعيل العرض بحركة الهاتف · حرّك هاتفك للنظر حولك.',motionDenied:'لم يُسمح بالوصول إلى حركة الهاتف. لا يزال بإمكانك السحب للنظر حولك.',fullscreenUnavailable:'ملء الشاشة غير متاح في هذا المتصفح.',tourLoadError:'تعذّر تحميل الجولة.',checkConnection:'تحقق من اتصالك ثم أعد تحميل الصفحة.',retry:'إعادة المحاولة',campusGuide:'دليل الحرم الجامعي PDF ↗',switchLanguage:'التبديل إلى الإنجليزية'
  }
};
